Fix formatting in build.sh for podman build command extra spaces
there are extra spaces causing error during build
+ echo '#### Building a new bootc image with MicroShift and application Container images embeeded to it'

#### Building a new bootc image with MicroShift and application Container images embeeded to it

+ sudo podman build -t microshift-bootc-embeeded:4.19 --volume /etc/rhsm:/etc/rhsm:ro,z --volume /etc/pki/entitlement:/etc/pki/entitlement:ro,z --volume /etc/containers/registries.d/registry-5000.yaml:/etc/containers/registries.d/registry-5000.yaml:ro,z ' '

Error: context must be a directory: "/home/lab-user/bootc-embeeded-containers/ "